// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'fullName': string;
  'gender': string;
  'qualityProfileId': string;
  'rootFolderPath': string;
  'status': string;
  'tags': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
