version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: "eros"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: "eros"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "develop"

