// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folderStructure': string;
  'folderStructureHeading': string;
  'sceneImportHaveMore': string;
  'sceneImportNote': string;
  'sceneImportStep': string;
}
export const cssExports: CssExports;
export default cssExports;
