// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'footer': string;
  'modalBody': string;
  'pageInfo': string;
  'pageText': string;
  'pagination': string;
  'scroller': string;
  'selectionInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
