// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'genres': string;
  'movieStatus': string;
  'originalLanguage': string;
  'path': string;
  'qualityProfileId': string;
  'releaseDate': string;
  'rottenTomatoesRating': string;
  'runtime': string;
  'sizeOnDisk': string;
  'sortTitle': string;
  'status': string;
  'studio': string;
  'tags': string;
  'tmdbRating': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
