// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'imdbId': string;
  'performers': string;
  'releaseDate': string;
  'studioTitle': string;
  'title': string;
  'tmdbId': string;
}
export const cssExports: CssExports;
export default cssExports;
