// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'qualityProfileId': string;
  'rootFolderPath': string;
  'sortTitle': string;
  'status': string;
  'tags': string;
}
export const cssExports: CssExports;
export default cssExports;
