// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'addButton': string;
  'addImportExclusion': string;
  'checkboxContainer': string;
  'foreignId': string;
  'importExclusionDropdownContainer': string;
  'importExclusionFilterForm': string;
  'importExclusionInfoContainer': string;
  'importExclusionRow': string;
  'importListExclusionsHeader': string;
  'title': string;
  'type': string;
}
export const cssExports: CssExports;
export default cssExports;
