// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonContainer': string;
  'buttonContainerContent': string;
  'buttons': string;
  'deleteSelectedButton': string;
  'inputContainer': string;
  'organizeSelectedButton': string;
  'selectedSeriesLabel': string;
  'tagsButton': string;
}
export const cssExports: CssExports;
export default cssExports;
