// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitlesIconContainer': string;
  'backdrop': string;
  'backdropOverlay': string;
  'certification': string;
  'contentContainer': string;
  'details': string;
  'detailsLabel': string;
  'errorMessage': string;
  'filterIcon': string;
  'genres': string;
  'header': string;
  'headerContent': string;
  'info': string;
  'innerContentBody': string;
  'links': string;
  'monitorToggleButton': string;
  'movieNavigationButton': string;
  'movieNavigationButtons': string;
  'network': string;
  'overview': string;
  'path': string;
  'poster': string;
  'qualityProfileName': string;
  'rating': string;
  'runtime': string;
  'selectedTab': string;
  'sizeOnDisk': string;
  'statusName': string;
  'studio': string;
  'tab': string;
  'tabContent': string;
  'tabList': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
  'year': string;
  'years': string;
}
export const cssExports: CssExports;
export default cssExports;
